"""Property-based test for pipeline idempotency.

# Feature: rebridge-backend, Property 11: Pipeline processing is idempotent

Property 11 (design.md): *For any* grading submission, running the pipeline a
second time with the same Idempotency_Key SHALL retain the existing persisted
grade unchanged and SHALL NOT re-invoke the Grading_Engine.

**Validates: Requirements 7.3**

The test drives the real :class:`GradingPipeline` against the in-memory fakes
(no AWS, no mocks). For an arbitrary grading submission it:

* runs the pipeline once, recording the first terminal outcome, the persisted
  grade, and every side effect it produced;
* runs the *same* :class:`GradingMessage` ``N`` more times (``N`` in 1..4);
* asserts each subsequent run reports ``SKIPPED_IDEMPOTENT`` and returns the
  grade from the first run;
* asserts the persisted grade is byte-for-byte unchanged after all runs;
* asserts the Grading_Engine (the scripted :class:`FakeGradingProvider`) is
  invoked exactly once across all runs -- never re-invoked on a duplicate;
* asserts no duplicated side effects: a high-confidence (GRADED) submission
  ends with exactly one GRADED event, exactly one router invocation, a single
  persisted Health Card and no review entry; a low-confidence (PENDING_REVIEW)
  submission ends with exactly one review entry (unchanged priority), no events
  and no routing.

The grade and confidence are varied so both gate branches are exercised. The
provider is scripted with *distinct* responses per call so that any spurious
re-invocation would both bump the call count and risk changing the grade --
making a non-idempotent pipeline fail loudly.
"""

from __future__ import annotations

from decimal import Decimal

from hypothesis import given, settings
from hypothesis import strategies as st

from rebridge_data.models import GradingMessage, ItemMeta, ItemStatus

from rebridge_service.confidence_gate import ConfidenceGate
from rebridge_service.eventing_service import EventingService
from rebridge_service.grade_schema import serialize_grade_assessment
from rebridge_service.grading_engine import GradingEngine
from rebridge_service.grading_pipeline import GradingPipeline, PipelineOutcome
from rebridge_service.health_card_service import HealthCardService
from rebridge_service.models import (
    CompletenessResult,
    Defect,
    Grade,
    GradeAssessment,
)
from rebridge_service.quality_precheck import QualityPrecheck

from tests.fakes import (
    FakeCardSigner,
    FakeEventPublisher,
    FakeGradingProvider,
    FakeItemRepository,
    FakeObjectStore,
    FakeReviewQueueRepository,
)

# Minimum iterations per the spec's property-testing guideline.
_ITERATIONS = 200

ITEM_ID = "item-idem"
PHOTO_KEYS = ["items/item-idem/photo-0", "items/item-idem/photo-1"]
EST_VALUE = Decimal("100")
THRESHOLD = 0.80

# High-contrast checkerboard: sharp + well-exposed -> passes the precheck so we
# always reach the grading engine on the first run.
SHARP_PIXELS = [[255 if (r + c) % 2 == 0 else 0 for c in range(5)] for r in range(5)]


def _decoder(_raw: bytes):
    return SHARP_PIXELS


def _assessment(grade: Grade, confidence: float) -> GradeAssessment:
    return GradeAssessment(
        grade=grade,
        defects=[Defect(location="corner", severity="minor")],
        completeness=CompletenessResult(is_complete=True, missing_components=[]),
        confidence=confidence,
        summary="generated by property test",
    )


def _valid_json(grade: Grade, confidence: float) -> str:
    return serialize_grade_assessment(_assessment(grade, confidence))


class _RecordingRouter:
    """Records route() invocations and returns a decision with a disposition."""

    def __init__(self) -> None:
        self.routed: list[str] = []

    def route(self, item_id: str):
        self.routed.append(item_id)
        return type("Decision", (), {"disposition": "RESELL"})()


def _build(grade: Grade, confidence: float):
    """Wire a pipeline whose provider is scripted with distinct responses.

    The script's first element carries the (grade, confidence) under test; the
    second carries a *different* grade. Because the engine must only ever be
    invoked on the first run, the second element should never be consumed -- if
    it were, both the call count and the persisted grade could change, failing
    the idempotency assertions.
    """

    item_repo = FakeItemRepository()
    item_repo.put_item_meta(
        ItemMeta(
            item_id=ITEM_ID,
            status=ItemStatus.CREATED,
            category="electronics",
            age_months=10,
            context_source="manual",
            created_at="2024-01-01T00:00:00+00:00",
        )
    )
    store = FakeObjectStore()
    for key in PHOTO_KEYS:
        store.put_object(key, b"good")
    review_repo = FakeReviewQueueRepository()
    publisher = FakeEventPublisher()

    # A decoy second response with a grade distinct from the one under test, so
    # an erroneous re-invocation would be observable as a changed grade.
    decoy = Grade.UNSELLABLE if grade is not Grade.UNSELLABLE else Grade.LIKE_NEW
    provider = FakeGradingProvider(
        "nova",
        script=[_valid_json(grade, confidence), _valid_json(decoy, 0.99)],
    )
    engine = GradingEngine([provider], timeout=None, max_json_retries=2)
    router = _RecordingRouter()
    pipeline = GradingPipeline(
        item_repo=item_repo,
        object_store=store,
        review_repo=review_repo,
        precheck=QualityPrecheck(),
        grading_engine=engine,
        confidence_gate=ConfidenceGate(threshold=THRESHOLD),
        card_service=HealthCardService(FakeCardSigner(), item_repo),
        eventing=EventingService(publisher),
        router=router,
        pixel_decoder=_decoder,
        value_estimator=lambda meta, assessment: EST_VALUE,
        catalog_provider=None,
    )
    return pipeline, item_repo, review_repo, publisher, provider, router


def _message() -> GradingMessage:
    return GradingMessage(
        item_id=ITEM_ID, idem_key="idem-key-1", photo_keys=list(PHOTO_KEYS)
    )


@settings(max_examples=_ITERATIONS)
@given(
    grade=st.sampled_from(list(Grade)),
    confidence=st.floats(min_value=0.0, max_value=1.0, allow_nan=False),
    extra_runs=st.integers(min_value=1, max_value=4),
)
def test_pipeline_processing_is_idempotent(
    grade: Grade, confidence: float, extra_runs: int
) -> None:
    """Re-running a submission retains the grade and never re-grades.

    Validates Requirement 7.3 / Property 11. ``extra_runs`` covers running the
    pipeline twice through five times total with the same GradingMessage.
    """

    pipeline, item_repo, review_repo, publisher, provider, router = _build(
        grade, confidence
    )
    message = _message()

    # -- first run establishes the persisted grade and its side effects -----
    first = pipeline.run(message)
    # A passing precheck + conforming JSON always reaches one of the two gate
    # branches on the first run.
    assert first.outcome in (PipelineOutcome.GRADED, PipelineOutcome.PENDING_REVIEW)

    first_grade = item_repo.get_grade(ITEM_ID)
    assert first_grade is not None

    # Snapshot the side effects produced by the single legitimate run.
    events_after_first = [e.event_type for e in publisher.events]
    routed_after_first = list(router.routed)
    pending_after_first = review_repo.list_pending(10)
    card_after_first = item_repo.get_item(ITEM_ID).card
    status_after_first = item_repo.get_item(ITEM_ID).meta.status

    # The engine was invoked exactly once to produce this grade.
    assert len(provider.calls) == 1

    # -- N subsequent identical runs must all be idempotent skips -----------
    for _ in range(extra_runs):
        again = pipeline.run(message)
        assert again.outcome is PipelineOutcome.SKIPPED_IDEMPOTENT
        # The skip returns the grade from the first run, unchanged.
        assert again.grade == first_grade

    # -- the persisted grade is unchanged after all runs --------------------
    assert item_repo.get_grade(ITEM_ID) == first_grade

    # -- the Grading_Engine was never re-invoked on a duplicate -------------
    assert len(provider.calls) == 1

    # -- no duplicated side effects: state matches the single first run -----
    assert [e.event_type for e in publisher.events] == events_after_first
    assert router.routed == routed_after_first
    assert review_repo.list_pending(10) == pending_after_first
    assert item_repo.get_item(ITEM_ID).card == card_after_first
    assert item_repo.get_item(ITEM_ID).meta.status is status_after_first

    # -- branch-specific shape of those (single) side effects ---------------
    if first.outcome is PipelineOutcome.GRADED:
        assert first_grade.confirmed is True
        assert events_after_first == ["GRADED"]  # exactly one GRADED event
        assert routed_after_first == [ITEM_ID]  # routed exactly once
        assert card_after_first is not None  # a single Health Card
        assert pending_after_first == []  # no review entry
        assert status_after_first is ItemStatus.GRADED
    else:  # PENDING_REVIEW
        assert first_grade.confirmed is False
        assert len(pending_after_first) == 1  # exactly one review entry
        assert events_after_first == []  # no lifecycle event
        assert routed_after_first == []  # router never invoked
        assert status_after_first is ItemStatus.PENDING_REVIEW
