"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect, useRef } from "react";
import gsap from "gsap";
import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";
import { prefersReducedMotion } from "@/lib/motion";

const LINES = ["Every product", "finds its", "next owner."];

/**
 * Hero — the real landing hero. Editorial sneaker image (Higgsfield-generated)
 * on the right, towering Archivo headline on the left, two real CTAs that go to
 * Market and Resell (not into a demo flow). A scroll cue invites the visitor
 * down into "How it works" / live demo / economics. GSAP masked rise on the
 * headline; reduced-motion collapses to the composed state.
 */
export function Hero() {
  const headlineRef = useRef<HTMLHeadingElement>(null);
  const scanRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const reduced = prefersReducedMotion();
    if (headlineRef.current) {
      const spans = headlineRef.current.querySelectorAll("[data-line] > span");
      if (reduced) {
        gsap.set(spans, { yPercent: 0, opacity: 1 });
      } else {
        gsap.fromTo(
          spans,
          { yPercent: 110, opacity: 0 },
          { yPercent: 0, opacity: 1, duration: 0.9, ease: "power3.out", stagger: 0.11 },
        );
      }
    }
    // Endless scan sweep over the hero image (decorative, on the dark stage).
    if (scanRef.current && !reduced) {
      const tween = gsap.fromTo(
        scanRef.current,
        { xPercent: -40, opacity: 0 },
        { xPercent: 100, opacity: 1, duration: 3.8, ease: "power1.inOut", repeat: -1, yoyo: false, repeatDelay: 1.6 },
      );
      return () => {
        tween.kill();
      };
    }
  }, []);

  return (
    <section
      data-testid="hero"
      className="relative overflow-hidden bg-canvas-warm px-4 pt-12 sm:px-6 sm:pt-20"
    >
      <div className="pointer-events-none absolute right-[-6%] top-[6%] select-none font-display text-[clamp(140px,26vw,360px)] font-black uppercase leading-[0.8] tracking-[-0.05em] text-ink/[0.03]">
        RE·USE
      </div>

      <div className="relative mx-auto grid max-w-[1200px] items-center gap-10 pb-20 lg:grid-cols-[1.05fr_1fr] lg:gap-16 lg:pb-28">
        <div>
          <div className="font-mono text-[12px] font-bold uppercase tracking-[0.24em] text-amber-deep">
            ReBridge · HackOn with Amazon S6
          </div>
          <h1
            ref={headlineRef}
            data-testid="hero-headline"
            className="mt-5 max-w-[14ch] font-display text-[clamp(46px,9vw,108px)] font-black uppercase leading-[0.92] tracking-[-0.035em]"
          >
            {LINES.map((line, i) => (
              <span key={i} data-line className="block overflow-hidden">
                <span className="block">
                  {i === 2 ? (
                    <>
                      next <span className="text-amber-deep">owner.</span>
                    </>
                  ) : (
                    line
                  )}
                </span>
              </span>
            ))}
          </h1>

          <p className="mt-6 max-w-[54ch] text-[16px] leading-relaxed text-ash">
            Photograph any returned, unused, or outgrown product. Our AI grades it
            for ₹3, prints a verifiable Health Card, and routes it to the right
            next owner — resale, refurb, peer-to-peer, or donation — in seconds.
          </p>

          <div className="mt-8 flex flex-wrap gap-3">
            <Link href="/market" data-testid="cta-market">
              <Button variant="primary" size="lg">
                Browse Second Chance
              </Button>
            </Link>
            <Link href="/resell" data-testid="cta-resell">
              <Button variant="secondary" size="lg">
                Resell an item <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
          </div>

          <a
            href="#how-it-works"
            className="mt-10 inline-flex items-center gap-2 font-sans text-[12px] font-bold uppercase tracking-[0.16em] text-mute hover:text-ink"
            data-testid="scroll-cue"
          >
            See how it works ↓
          </a>
        </div>

        {/* Hero image — generated by Higgsfield (editorial sneaker on dark stage). */}
        <div
          data-testid="hero-image"
          className="relative aspect-[16/12] w-full overflow-hidden rounded-card border border-white/10 bg-[#0e0e10] shadow-lg lg:aspect-[5/4]"
        >
          <Image
            src="/hero/sneaker.png"
            alt="A worn running sneaker lit on a dark editorial stage — the ReBridge inspection moment"
            fill
            priority
            sizes="(min-width: 1024px) 540px, 100vw"
            className="object-cover"
          />
          {/* decorative amber scan sweep on top of the hero image */}
          <div
            ref={scanRef}
            className="pointer-events-none absolute inset-y-0 w-[80px]"
            style={{
              background:
                "linear-gradient(90deg,transparent,rgba(255,153,0,.25),transparent)",
              boxShadow: "0 0 30px 4px rgba(255,153,0,.25)",
              left: 0,
            }}
          />
          <div className="pointer-events-none absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 to-transparent p-4">
            <div className="flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-amber/90">
              <span className="h-1.5 w-1.5 animate-pulse2 rounded-full bg-amber" />
              ₹3 inspection · in progress
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
